services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: nzhuzhle
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
      CSV_PATH: ${CSV_PATH}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ${CSV_PATH}:/csv_data:ro

volumes:
  db_data: